### ISSUE TITLE
Deno deploy support?

### ISSUE THREAD

**Issue by DefinitelyMaybe** [pluvial/svelte-adapter-deno#11]
Howdy!

I ran through quickly setting up a new sveltekit project, added the deno adapter and wanted to deploy it straight away into deno deploy but it came up with the following error:
```
TypeError: Deno.lstatSync is not a function
    at existsSync (https://deno.land/std@0.106.0/fs/exists.ts:19:14)
    at createServer (file:///src/dist/index.js:2229:31)
    at file:///src/dist/index.js:2266:16
```
Is supporting deno deploy a direction that ya'll want to go in?

edit: [Here's a link to the project](https://github.com/DefinitelyMaybe/laughing-computing-machine) if you'd like to take a look

**Comment by jpaquim** [comment]
Hey @DefinitelyMaybe ! I still need to give Deno Deploy a serious try, and haven't really experimented with running this adapter within that environment. It may make sense to create a separate adapter for that purpose, maybe a bit more similar to https://github.com/sveltejs/kit/tree/master/packages/adapter-cloudflare-workers

How has your experience been so far? Did you manage to get something working?

**Comment by jpaquim** [comment]
Great, let me know when you have something available and I'll try to contribute :smiley: I'll test drive Deno Deploy more seriously one of these days.

**Comment by DefinitelyMaybe** [comment]
OMGosh!!!!! amazing! thank you thank you thank you!

I can use this within a project I've got coming up
