### ISSUE TITLE
Looking for clarity about the use-case of this project

### ISSUE THREAD

**Issue by oren** [pluvial/svelte-adapter-deno#26]
Context: I would like to build a website with svelte kit that makes calls to HTTP API written in Deno and some DB to store some state about the users. Probably key-value store. I would like to explore the most efficient setup (resources, money). I am familiar with the basics of Svelte but not with Deno.

How would the development experience looks like, how would the deployment experience looks like and how would a production setup looks like? Are we talking about a single codebase with server folder and a client folder that are deployed to the host and also a Caddy (or reverse proxy) in front of them? and the way to access them is my-app.com and api.my-app.com?

Are there simpler solutions? and is this project even relevant to my usecase?

**Comment by jpaquim** [comment]
Hey there @oren! Thanks for your questions, I'll try to give an overview:

This package is very similar to other [SvelteKit adapters](https://kit.svelte.dev/docs/adapters), like [@sveltejs/adapter-node](https://github.com/sveltejs/kit/tree/master/packages/adapter-node) and [@sveltejs/adapter-vercel](https://github.com/sveltejs/kit/tree/master/packages/adapter-vercel).

It essentially generates a standalone Deno server from a SvelteKit application, but is only relevant during a production build, for deployment: during development SvelteKit will only run its own Node.js + Vite development server, no matter what adapter you use.

As for deployment solutions, it should work on any environment that supports Deno (your own server, a VPS, a PaaS that supports Deno, etc.). The "blessed" way to deploy would be using Deno's own Deno Deploy service: https://deno.com/deploy

You can check out the [example in this repo](https://github.com/pluvial/svelte-adapter-deno/tree/main/examples/svelte-kit-demo). It's being deployed on Deno Deploy using this [GitHub action](https://github.com/pluvial/svelte-adapter-deno/blob/main/.github/workflows/ci.yml), here: https://svelte-adapter-deno.deno.dev

For your use case in particular, I guess it depends on whether SvelteKit itself makes sense for your project. SvelteKit is designed for these kinds of modern serverless/edge environments, if you don't need any platform-specific code, you can even deploy the same codebase to multiple platforms with minimal effort, which I'm taking advantage of here: https://github.com/pluvial/pluvial.xyz#deployments

Do take into consideration that while SvelteKit supports API endpoints, it may be better to go for a more full-fledged API framework for your project, depending on its complexity.

**Comment by oren** [comment]
thank you so much João. You reply shows me how much complexity involved in modern software development. I'll look into all your links and recommendations.
