### ISSUE TITLE
Default deps.ts file is not included in the NPM package

### ISSUE THREAD

**Issue by heliumbrain** [pluvial/svelte-adapter-deno#3]
Hi again,

It seems like your NPM package does not include the default `deps.ts` that is in this repo. Following the instructions in the README fails on `deno run` since there is no `deps.ts` file to read from.

If I copy the `deps.ts` from the repo and add it to my project root before `npm run build` it gets picked up and copied over to the build folder.

Is this intended? If so, you might want to update the README to state that you need to create `deps.ts`yourself. If not, add it to the `files` section in package.json so it get's included in the NPM package.

**Comment by heliumbrain** [comment]
Just want to mention that after adding the `deps.ts`file as mentioned in this issue and the fix in PR #2. Everything is working smoothly and the deno server is running fine 👍

**Comment by jpaquim** [comment]
Thanks for the heads up! I addressed it in a PR, and published a new version, hopefully it should work out of the box now!
