### ISSUE TITLE
What should I do if I already have a Deno app?

### ISSUE THREAD

**Issue by lukepuplett** [pluvial/svelte-adapter-deno#33]
I'm from ASP.NET Core and am learning Deno, oak and looking at the newer breed of JS frameworks.

I've struggled immensely with Svelte because I can't understand how it fits into my mental model of a web app. I don't understand how my existing Deno app serves the Svelte content that, I think, Vite produces.

I'd expect there to be Svelte middleware, or maybe I render some outer HTML via Eta and put some Svelte JS entrypoint in that. I don't know.

I'm also not used to coding via a dev HTTP server that isn't the actual web server (and so doesn't have my middleware in effect).

I was told to research Svelte Adapters and here I am. This adapter appears to emit the whole Deno app? Is that right (I'm a noob)? So I can't integrate Svelte with an existing Deno app serving some other pages and static files?

Thanks for any advice :)

**Comment by jpaquim** [comment]
Hello @lukepuplett! Thanks for your question, I'll try to answer clearly.

> This adapter appears to emit the whole Deno app? Is that right (I'm a noob)?

Yes, it is primarily designed to generate a bundle that serves as the entrypoint for your app. It is definitely not as extensible as it can (and should) be. However, it does expose the Oak handler as defined in https://github.com/pluvial/svelte-adapter-deno/blob/main/src/handler.js so you can use that instead in your application to add svelte-adapter-deno's SSR and static file serving. This is relatively untested, but it should behave similarly to the equivalent Node middleware as describe here: https://github.com/sveltejs/kit/tree/master/packages/adapter-node#custom-server

If you do not need SSR and only want to serve static files using Deno, I'd recommend using SvelteKit's `adapter-static` to generate all the .html, .js, .css, etc. files you need, and using something like the `serveDirectory()` logic here: https://github.com/pluvial/svelte-adapter-deno/blob/main/src/handler.js#L12

If you are relatively comfortable with JS, you should be able to read this adapter's src/ code for inspiration, it's really very short.

There are few other aspects in which this adapter could be made more extensible, so if you do go down this route, I'd expect more feedback on how I could make it better 😄

**Comment by lukepuplett** [comment]
Thank you, João! That's clear and very useful, and good to know it uses Oak. I'll close this issue.
