### ISSUE TITLE
Environment variables ($env/static/private)

### ISSUE THREAD

**Issue by r-moore** [pluvial/svelte-adapter-deno#43]
SvelteKit supports [loading environment variables](https://learn.svelte.dev/tutorial/env-static-private) by importing from `$env`,  but these don't seem to work on Deno Deploy

Maybe because deno uses `Deno.env` rather than `import.meta.env` so the adapter would need to translate any references?

**Comment by 205g0** [comment]
@jpaquim any news on this?

**Comment by happysalada** [comment]
also interested.

**Comment by Peyman-Borhani** [comment]
@r-moore @205g0 
This might be useful:
https://github.com/denoland/deno/issues/17248#issuecomment-1634413871

**Comment by benmccann** [comment]
You could take a look at what this other Deno adapter does: https://github.com/dbushell/sveltekit-adapter-deno/blob/1cc7abd1699c0e978728848f8cc52e41d73228bf/files/mod.ts#L6
