### ISSUE TITLE
`Broken pipe (os error 32)` if cancellig request

### ISSUE THREAD

**Issue by Tc-001** [pluvial/svelte-adapter-deno#5]
# How to reproduce

1. Start a server
2. Navigate to localhost:3000
3. Cancel page load (hitting the "X" button in place of reload, or any other disconnection)
4. Server crashes

```
> deno run -A ./build/server.js
Listening on port 3000
# (Cancelling a load)
error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32)
          numBytesWritten = await this.writer.write(data);
                            ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at async write (deno:extensions/net/01_net.js:26:12)
    at async BufWriter.write (https://deno.land/std@0.95.0/io/bufio.ts:501:29)
    at async writeResponse (https://deno.land/std@0.95.0/http/_io.ts:275:15)
    at async ServerRequest.respond (https://deno.land/std@0.95.0/http/server.ts:87:7)
    at async Response.end (https://deno.land/x/opine@1.3.3/src/response.ts:256:7)
```

It seems to be the the same issue described here: https://github.com/denoland/deno_std/issues/659#issuecomment-800419398, where the error will happen, but is not correctly caught, thus the crash.

Probably some part of `server.js` needs to be wrapped in a trycatch to prevent it crashing the entire server (the traceback couldn't be less useful), but other than that I don't know what could be done (without going upstream to opine, and that seems to be already done: https://github.com/asos-craigmorten/opine/issues/102#issuecomment-868382619)

**Comment by jpaquim** [comment]
Thanks for catching and reporting this 🙏 I'll follow the upstream opine issue, and leave this open here until an updated version is available.

**Comment by Tc-001** [comment]
Fixed with https://github.com/asos-craigmorten/opine/pull/135
