### ISSUE TITLE
update body

### ISSUE THREAD

**Issue by benmccann** [pluvial/svelte-adapter-deno#7]
See https://github.com/sveltejs/kit/pull/2215

I didn't look closely, but you might need to update this line: https://github.com/pluvial/svelte-adapter-deno/blob/186757dfbff37af1fe9eeb086b140a60913bbf31/src/http.js#L16

This is the last breaking change on the 1.0 milestone affecting SvelteKit adapters, so while no promises, hopefully there won't be any more changes required after this

Thanks for providing this adapter!

**Comment by jpaquim** [comment]
Hey @benmccann, thanks for your input! If I understand correctly, the change I added here should be enough: https://github.com/pluvial/svelte-adapter-deno/pull/10/files#diff-9097bfe5ae868eccdb921b5a043bd3bc4087e8aacd257640ab51f1513baae7b4R14

**Comment by benmccann** [comment]
I didn't look super closely, but looks good to me
